# Generated by Django 6.1.1 on 2026-10-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default="Semurg' TORT Markazi", max_length=100, verbose_name='Nomi'),
        ),
    ]
