# Generated by Django 6.1.1 on 2026-09-30 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='F.I.O')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon +998 XX XXX XX XX ko'rinishida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=60, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kuni")),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh (allergiya, xohish)')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP mijoz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Login')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
