# Generated by Django 6.1.1 on 2026-09-30 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cakes', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='Ism')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 yulduz'), (2, '2 yulduz'), (3, '3 yulduz'), (4, '4 yulduz'), (5, '5 yulduz')], default=5, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Baho')),
                ('text', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Sharh')),
                ('is_published', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Javob berilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan')),
                ('cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cakes.cake', verbose_name='Tort')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='clients.client', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
