"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load settings from .env file if it exists
# Boshqa fayl kerak bo'lsa: DJANGO_ENV_FILE=.env.production
load_dotenv(BASE_DIR / os.environ.get('DJANGO_ENV_FILE', '.env'))


# SECURITY: maxfiy kalit .env da bo'lishi shart. Kod ichida saqlanmaydi.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY or SECRET_KEY.startswith('django-insecure-'):
    if os.environ.get('DJANGO_DEBUG', '').lower() not in ('true', '1', 'yes'):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY ni .env fayliga yozing "
            "(python -c \"import secrets; print(secrets.token_urlsafe(50))\")"
        )
    # Faqat lokal ishlab chiqish uchun vaqtinchalik kalit
    SECRET_KEY = 'dev-only-insecure-key-do-not-use-in-production'

DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# '*' production da xavfsiz — har doim aniq domenlarni yozing.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost'
    ).split(',') if h.strip()
]
if DEBUG:
    ALLOWED_HOSTS += ['testserver']

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CORS_ORIGINS', '').split(',')
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # API
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Project apps
    'core',
    'clients',
    'cakes',
    'orders',
    'reviews',

    # Sayt ichidagi boshqaruv paneli
    'panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Saytni faqat ro'yxatdan o'tganlarga ochadi (kirish/register ochiq).
    'core.middleware.RequireLoginMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
                'core.context_processors.cart_badge',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Hosting (Render, Railway, VPS) PostgreSQL manzilini DATABASE_URL orqali beradi,
# masalan: postgresql://user:pass@host:5432/dbname
# Berilmasa lokal SQLite ishlatiladi.
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

if DATABASE_URL:
    parsed = urlparse(DATABASE_URL)
    db_name = parsed.path.lstrip('/')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': unquote(parsed.username or ''),
            'PASSWORD': unquote(parsed.password or ''),
            'HOST': parsed.hostname or '',
            'PORT': str(parsed.port or 5432),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {'sslmode': os.environ.get('SSLMODE', 'require')},
        }
    }
    if not db_name:
        raise ImproperlyConfigured(
            "DATABASE_URL da bazaning nomi yo'q (postgresql://foydalanuvchi:parol@host:5432/bazanomi)"
        )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'uz-uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# nginx yo'q bo'lgan hostingda (masalan PythonAnywhere, Render, tunnel)
# statik fayllarni WhiteNoise beradi — alohida nginx shart emas.
if not DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Media fayllarini ham Django berishi (nginx/WhiteNoise faqat static beradi).
# Ochiq hostingda rasm ko'rinishi uchun yoqiladi.
MEDIA_VIA_DJANGO = os.environ.get(
    'MEDIA_VIA_DJANGO', '').lower() in ('true', '1', 'yes')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Autentifikatsiya

LOGIN_URL = 'clients:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

# Saytni faqat ro'yxatdan o'tgan (kirgan) foydalanuvchilar ko'radi.
# DJANGO_DEBUG qat'iy o'chirilgan bo'lsa ham ochiq qolmaydi —
# sayt yopiq bo'lishi kerak bo'lsa True qoldiring.
SITE_REQUIRE_LOGIN = os.environ.get(
    'SITE_REQUIRE_LOGIN', 'True').lower() in ('true', '1', 'yes')

# Boshqaruv paneli manzili (config/urls.py ham shundan foydalanadi).
PANEL_URL_PREFIX = '/boshqaruv/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Django 6.1 da EMAIL eskirgan (Django 7.0 da o'chiriladi) — MAILERS ishlatiladi.
# Lokal/preview da xabarlar konsolga chiqadi.
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
DEFAULT_FROM_EMAIL = 'noreply@semurog-tort.uz'


# REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Brute-force va spam'ga qarshi
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',
        'user': '300/hour',
        'login': '10/hour',
        'register': '10/day',
        'checkout': '20/hour',
        'cart': '120/hour',
        'contact': '10/hour',
        'review': '10/day',
    },
}


# CORS — frontend boshqa portda bo'lsa kerak

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'DJANGO_CORS_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000',
    ).split(',') if o.strip()
]

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS


# ---------------------------------------------------------------------------
# Xavfsizlik (production uchun avtomatik qattiqroq qilinadi)
# ---------------------------------------------------------------------------

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14          # 2 hafta
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Yuklanayotgan fayl hajmini cheklash (DoS ga qarshi)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# ---------------------------------------------------------------------------
# Telegram bot orqali markazga xabar yuborish
# orders/services.py shu sozlamalarni o'qiydi.
# TELEGRAM_CHAT_ID bir nechta bo'lishi mumkin: "123,456"
# ---------------------------------------------------------------------------

TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '').strip()
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '').strip()
TELEGRAM_TIMEOUT = int(os.environ.get('TELEGRAM_TIMEOUT', '8'))


# ---------------------------------------------------------------------------
# Sayt manzili (Telegram xabarlaridagi havolalar uchun)
# ---------------------------------------------------------------------------

SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000').rstrip('/')


# ---------------------------------------------------------------------------
# Loglar — token/parol kabi maxfiy narsalar yozilmaydi
# ---------------------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'orders.services': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

