# Generated by Django 6.1.1 on 2026-09-30 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergenlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('group', models.CharField(default="O'lcham", max_length=50, verbose_name='Guruh')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Qo'shimcha narx")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Eski narxi')),
                ('weight_gram', models.PositiveIntegerField(default=0, verbose_name="Og'irligi (gramm)")),
                ('main_image', models.ImageField(upload_to='cakes/', verbose_name='Asosiy rasm')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinadi")),
                ('is_preorder', models.BooleanField(default=False, verbose_name='Faqat oldindan buyurtma')),
                ('min_order_days', models.PositiveSmallIntegerField(default=0, verbose_name='Kamida kun oldin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('allergens', models.ManyToManyField(blank=True, related_name='cakes', to='cakes.allergen', verbose_name='Allergenlar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakes.category', verbose_name='Kategoriya')),
                ('options', models.ManyToManyField(blank=True, related_name='cakes', to='cakes.option', verbose_name='Variantlar')),
            ],
            options={
                'verbose_name': 'Tort',
                'verbose_name_plural': 'Tortlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cakes/gallery/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cakes.cake')),
            ],
            options={
                'verbose_name': 'Tort rasmi',
                'verbose_name_plural': 'Tort rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='cake',
            index=models.Index(fields=['category', 'is_active'], name='cakes_cake_categor_5f3f06_idx'),
        ),
        migrations.AddIndex(
            model_name='cake',
            index=models.Index(fields=['price'], name='cakes_cake_price_560dbb_idx'),
        ),
    ]
