# Generated by Django 6.1.1 on 2026-09-30 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cakes', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('discount_percent', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma %')),
                ('min_order_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimal summa')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanishi')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Tugashi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan')),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
                'ordering': ['-used_count', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi'), ('in_progress', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=20, verbose_name='Holat')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('click', 'Click / Payme')], default='cash', max_length=10, verbose_name="To'lov")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'landi")),
                ('delivery_address', models.TextField(verbose_name='Yetkazish manzili')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='Yetkazish sanasi')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Vaqt')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tovar summasi')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yetkazib berish')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='Mijoz')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Promo kod')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Yozuv')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cakes.cake', verbose_name='Tort')),
                ('options', models.ManyToManyField(blank=True, to='cakes.option', verbose_name='Variantlar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Buyurtma tarkibi',
                'verbose_name_plural': 'Buyurtma tarkiblari',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
    ]
